# Generated by Django 5.1.7 on 2026-02-25 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.TextField()),
                ('has_internet', models.BooleanField(default=False)),
                ('has_smartphone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSMEAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agents.agentprofile')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='smes.smeprofile')),
            ],
            options={
                'db_table': 'agent_sme_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('agent', 'sme')},
            },
        ),
    ]
