# Generated by Django 5.1.7 on 2026-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_foldable',
            field=models.BooleanField(default=False, help_text='Tick for clothing, fabric, or other soft items that can be folded/compressed into a small parcel. Forces delivery_size_category to SMALL unless packaging_override is set.'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_override',
            field=models.CharField(choices=[('none', 'None (use dimensional logic)'), ('small', 'Always Small'), ('medium', 'Always Medium'), ('large', 'Always Large')], default='none', help_text='Pin a specific PAXI size category, ignoring both dimensions and the foldable flag. Leave as "none" to use automatic logic.', max_length=10),
        ),
    ]
