# Generated by Django 6.0.3 on 2026-05-14 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0003_product_is_foldable_product_packaging_override'),
        ('smes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('small_items', 'Small Items (Clothing, accessories, jewellery)'), ('medium_items', 'Medium Items (Boxed goods, shoes, electronics)'), ('large_bulky', 'Large / Bulky Items (Furniture, bulk food, appliances)'), ('perishable_food', 'Perishable Food (Fresh produce, dairy, meat, bakery)')], default='', help_text='Category that determines the flat-rand commission fee.', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='urgency_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority (+R5)'), ('express', 'Express (+R15)')], default='standard', help_text='Delivery urgency — only affects perishable_food commission.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['commission_type'], name='products_commiss_c9429d_idx'),
        ),
    ]
