# Generated by Django 5.1.7 on 2026-05-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_commission_type_product_urgency_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urgency_level',
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('hair_cosmetics', 'Hair, Hair Products and Cosmetics'), ('clothing', 'Clothing'), ('shoes', 'Shoes'), ('fragrances', 'Fragrances'), ('local_handmade', 'Local Handmade Products'), ('cleaning_products', 'Cleaning Products (SABS)')], default='', help_text='Category that determines the commission percentage.', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_foldable',
            field=models.BooleanField(default=False, help_text='Tick for clothing, fabric, hair products, or other soft items that can be folded/compressed into a small parcel. Forces delivery_size_category to SMALL.'),
        ),
    ]
